name: Create Module Files For GitHub Release


env:
    project_url: "https://github.com/${{github.repository}}"
    latest_manifest_url: "https://github.com/${{github.repository}}/releases/latest/download/module.json"
    release_module_url: "https://github.com/${{github.repository}}/releases/download/${{github.event.release.tag_name}}/module.zip"


on:
    push:
        tags:
            - '*'


jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: write

        steps:
            -   name: Checkout Repository
                uses: actions/checkout@v3

            -   name: Build assets [1/2] - yarn install
                run: yarn install

            -   name: Build assets [2/2] - yarn build
                run: NODE_ENV=production yarn run build

            -   name: Modify Module Manifest With Release-Specific Values
                id: sub_manifest_link_version
                uses: cschleiden/replace-tokens@v1
                with:
                    files: 'module.json'
                env:
                    VERSION: ${{github.ref_name}}
                    URL: ${{ env.project_url }}
                    MANIFEST: ${{ env.latest_manifest_url }}
                    DOWNLOAD: ${{ env.release_module_url }}

            -   name: Create Module Archive
                run: |
                    zip                                    \
                      --recurse-paths                      \
                       ./module.zip                        \
                      module.json                          \
                      README.md                            \
                      CHANGELOG.md                         \
                      LICENSE                              \
                      templates                            \
                      assets/                              \
                      lang/

            -   name: Update Release With Files
                id: create_version_release
                uses: ncipollo/release-action@v1
                with:
                    allowUpdates: true
                    name: ${{ github.event.release.name }}
                    draft: ${{ github.event.release.unpublished }}
                    prerelease: ${{ github.event.release.prerelease }}
                    token: ${{ secrets.GITHUB_TOKEN }}
                    artifacts: './module.json, ./module.zip'
                    tag: ${{ github.event.release.tag_name }}
                    body: ${{ github.event.release.body }}
